name: CI/CD Pipeline a AWS EC2



on:
 push:
  branches:

   - deploy 

env:
 AWS_REGION: us-east-1
 CLUSTER: devops-u2-cluster
 SERVICE: app

jobs:
 build-and-deploy:
  runs-on: ubuntu-latest
  steps:
   - name: Checkout del código
    uses: actions/checkout@v3
   - name: Configurar las credenciales de AWS
    uses: aws-actions/configure-aws-credentials@v2
    with:
     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
     aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }} # Crítico para cuentas de AWS Academy
     aws-region: ${{ env.AWS_REGION }}
   - name: Login en AWS ECR

    id: login-ecr

    uses: aws-actions/amazon-ecr-login@v2

   - name: Build y Push Backend Ventas

    run: |

     docker build --platform linux/amd64 \

     -t ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/innovatech-back-ventas:latest \

     ./back-Ventas_SpringBoot/Springboot-API-REST

     docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/innovatech-back-ventas:latest



   - name: Build y Push Backend Despachos

    run: |

     docker build --platform linux/amd64 \

     -t ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/innovatech-back-despachos:latest \

     ./back-Despachos_SpringBoot/Springboot-API-REST-DESPACHO

     docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/innovatech-back-despachos:latest



   - name: Build y Push Frontend

    run: |

     docker build --platform linux/amd64 \

     -t ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/innovatech-frontend:latest \

     ./front_despacho

     docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/innovatech-frontend:latest

    

   - name: Desplegar en Instancia EC2

    uses: appleboy/ssh-action@master

    with:

     host: ${{ secrets.EC2_HOST }}

     username: ec2-user

     key: ${{ secrets.EC2_SSH_KEY }}

     script: |